export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  originalPrice?: number;
  imageUrl: string;
  images?: string[];
  category: string;
  categorySlug: string;
  description: string;
  shortDescription: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockCount: number;
  isNew?: boolean;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  isOnSale?: boolean;
  isDeal?: boolean;
  tags?: string[];
  colors?: string[];
  sizes?: string[];
  brand?: string;
  material?: string;
  createdAt: string;
}

export const featuredProducts: Product[] = [
  // --- Trouser ---
  {
    id: "trouser-1",
    name: "Premium Cotton Trouser",
    slug: "premium-cotton-trouser",
    price: 2800,
    originalPrice: 3200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description:
      "High-quality premium cotton trouser perfect for both formal and casual occasions. Made with finest fabric for maximum comfort and durability.",
    shortDescription: "Premium cotton trouser for everyday comfort",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    stockCount: 45,
    isFeatured: true,
    isBestSeller: true,
    isOnSale: true,
    isDeal: true,
    tags: ["comfort", "premium", "cotton"],
    colors: ["Black", "Navy", "Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand: "DeenCommerce",
    material: "100% Cotton",
    createdAt: "2024-01-15",
  },
  {
    id: "trouser-2",
    name: "Slim Fit Formal Trouser",
    slug: "slim-fit-formal-trouser",
    price: 2600,
    originalPrice: 3000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description:
      "Slim fit formal trouser for office and events. Wrinkle-resistant and easy to maintain.",
    shortDescription: "Slim fit formal trouser",
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    stockCount: 30,
    isFeatured: true,
    isOnSale: true,
    isDeal: true,
    tags: ["formal", "slim-fit"],
    colors: ["Black", "Gray"],
    sizes: ["30", "32", "34", "36"],
    brand: "DeenCommerce",
    material: "Polyester Blend",
    createdAt: "2024-01-18",
  },
  {
    id: "trouser-3",
    name: "Casual Chino Trouser",
    slug: "casual-chino-trouser",
    price: 2200,
    originalPrice: 2500,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description:
      "Casual chino trouser with stretchable fabric for all-day comfort.",
    shortDescription: "Casual chino trouser",
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    tags: ["casual", "chino"],
    colors: ["Beige", "Olive", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton-Spandex",
    createdAt: "2024-01-22",
  },
  {
    id: "trouser-4",
    name: "Classic Black Trouser",
    slug: "classic-black-trouser",
    price: 2400,
    originalPrice: 2700,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description: "Classic black trouser for versatile styling.",
    shortDescription: "Classic black trouser",
    rating: 4.7,
    reviewCount: 80,
    inStock: true,
    stockCount: 25,
    isFeatured: true,
    tags: ["classic", "black"],
    colors: ["Black"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Polyester",
    createdAt: "2024-01-25",
  },
  {
    id: "trouser-5",
    name: "Stretchable Jogger Trouser",
    slug: "stretchable-jogger-trouser",
    price: 2100,
    originalPrice: 2400,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description: "Jogger style trouser with elastic waistband and ankle cuffs.",
    shortDescription: "Stretchable jogger trouser",
    rating: 4.5,
    reviewCount: 55,
    inStock: true,
    stockCount: 35,
    isFeatured: true,
    tags: ["jogger", "stretchable"],
    colors: ["Gray", "Navy"],
    sizes: ["S", "M", "L"],
    brand: "DeenCommerce",
    material: "Cotton-Polyester",
    createdAt: "2024-01-28",
  },
  {
    id: "trouser-6",
    name: "Formal Navy Trouser",
    slug: "formal-navy-trouser",
    price: 2500,
    originalPrice: 2800,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description: "Formal navy trouser with slim fit cut.",
    shortDescription: "Formal navy trouser",
    rating: 4.3,
    reviewCount: 42,
    inStock: true,
    stockCount: 20,
    isFeatured: true,
    tags: ["formal", "navy"],
    colors: ["Navy"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Polyester",
    createdAt: "2024-02-01",
  },
  {
    id: "trouser-7",
    name: "Everyday Comfort Trouser",
    slug: "everyday-comfort-trouser",
    price: 2000,
    originalPrice: 2300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description: "Everyday comfort trouser for all-day wear.",
    shortDescription: "Everyday comfort trouser",
    rating: 4.2,
    reviewCount: 38,
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    tags: ["comfort", "everyday"],
    colors: ["Gray", "Beige"],
    sizes: ["S", "M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-05",
  },
  {
    id: "trouser-8",
    name: "Everyday Comfort Trouser",
    slug: "everyday-comfort-trouser",
    price: 2000,
    originalPrice: 2300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Trouser",
    categorySlug: "trouser",
    description: "Everyday comfort trouser for all-day wear.",
    shortDescription: "Everyday comfort trouser",
    rating: 4.2,
    reviewCount: 38,
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    tags: ["comfort", "everyday"],
    colors: ["Gray", "Beige"],
    sizes: ["S", "M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-05",
  },

  // --- Jeans ---
  {
    id: "jeans-1",
    name: "Classic Denim Jeans",
    slug: "classic-denim-jeans",
    price: 3500,
    originalPrice: 4000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description:
      "Classic fit denim jeans made from premium denim fabric. Features comfortable stretch and modern styling for the contemporary man.",
    shortDescription: "Classic fit denim jeans with modern styling",
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    stockCount: 32,
    isFeatured: true,
    isOnSale: true,
    tags: ["denim", "classic", "comfortable"],
    colors: ["Blue", "Black", "Dark Blue"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    brand: "DeenCommerce",
    material: "98% Cotton, 2% Elastane",
    createdAt: "2024-01-20",
  },
  {
    id: "jeans-2",
    name: "Slim Fit Blue Jeans",
    slug: "slim-fit-blue-jeans",
    price: 3400,
    originalPrice: 3900,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description: "Slim fit blue jeans for a modern look.",
    shortDescription: "Slim fit blue jeans",
    rating: 4.5,
    reviewCount: 77,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    tags: ["slim-fit", "blue"],
    colors: ["Blue"],
    sizes: ["30", "32", "34", "36"],
    brand: "DeenCommerce",
    material: "Denim",
    createdAt: "2024-01-23",
  },
  {
    id: "jeans-3",
    name: "Black Stretch Jeans",
    slug: "black-stretch-jeans",
    price: 3600,
    originalPrice: 4100,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description: "Black stretch jeans for extra comfort.",
    shortDescription: "Black stretch jeans",
    rating: 4.7,
    reviewCount: 65,
    inStock: true,
    stockCount: 22,
    isFeatured: true,
    tags: ["black", "stretch"],
    colors: ["Black"],
    sizes: ["32", "34", "36"],
    brand: "DeenCommerce",
    material: "Denim-Spandex",
    createdAt: "2024-01-26",
  },
  {
    id: "jeans-4",
    name: "Washed Blue Jeans",
    slug: "washed-blue-jeans",
    price: 3300,
    originalPrice: 3700,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description: "Washed blue jeans for a trendy look.",
    shortDescription: "Washed blue jeans",
    rating: 4.4,
    reviewCount: 54,
    inStock: true,
    stockCount: 19,
    isFeatured: true,
    tags: ["washed", "blue"],
    colors: ["Blue", "Light Blue"],
    sizes: ["30", "32", "34"],
    brand: "DeenCommerce",
    material: "Denim",
    createdAt: "2024-01-29",
  },
  {
    id: "jeans-5",
    name: "Dark Indigo Jeans",
    slug: "dark-indigo-jeans",
    price: 3700,
    originalPrice: 4200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description: "Dark indigo jeans for a bold style.",
    shortDescription: "Dark indigo jeans",
    rating: 4.3,
    reviewCount: 41,
    inStock: true,
    stockCount: 15,
    isFeatured: true,
    tags: ["indigo", "dark"],
    colors: ["Indigo"],
    sizes: ["32", "34", "36"],
    brand: "DeenCommerce",
    material: "Denim",
    createdAt: "2024-02-01",
  },
  {
    id: "jeans-6",
    name: "Ripped Denim Jeans",
    slug: "ripped-denim-jeans",
    price: 3900,
    originalPrice: 4400,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description: "Ripped denim jeans for a rugged look.",
    shortDescription: "Ripped denim jeans",
    rating: 4.2,
    reviewCount: 36,
    inStock: true,
    stockCount: 12,
    isFeatured: true,
    tags: ["ripped", "denim"],
    colors: ["Blue"],
    sizes: ["30", "32", "34"],
    brand: "DeenCommerce",
    material: "Denim",
    createdAt: "2024-02-04",
  },
  {
    id: "jeans-7",
    name: "Regular Fit Jeans",
    slug: "regular-fit-jeans",
    price: 3200,
    originalPrice: 3600,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Jeans",
    categorySlug: "jeans",
    description: "Regular fit jeans for everyday wear.",
    shortDescription: "Regular fit jeans",
    rating: 4.1,
    reviewCount: 29,
    inStock: true,
    stockCount: 10,
    isFeatured: true,
    tags: ["regular", "fit"],
    colors: ["Blue", "Black"],
    sizes: ["30", "32", "34", "36"],
    brand: "DeenCommerce",
    material: "Denim",
    createdAt: "2024-02-07",
  },

  // --- Panjabi ---
  {
    id: "panjabi-1",
    name: "Traditional Panjabi",
    slug: "traditional-panjabi",
    price: 2200,
    originalPrice: 2500,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description:
      "Elegant traditional panjabi crafted from soft cotton fabric. Perfect for religious occasions, festivals, and formal events.",
    shortDescription: "Elegant traditional panjabi for special occasions",
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    tags: ["traditional", "cotton", "elegant"],
    colors: ["White", "Cream", "Light Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand: "DeenCommerce",
    material: "100% Cotton",
    createdAt: "2024-02-01",
  },
  {
    id: "panjabi-2",
    name: "Cotton Panjabi",
    slug: "cotton-panjabi",
    price: 2100,
    originalPrice: 2400,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description: "Soft cotton panjabi for daily comfort.",
    shortDescription: "Soft cotton panjabi",
    rating: 4.7,
    reviewCount: 102,
    inStock: true,
    stockCount: 22,
    isFeatured: true,
    tags: ["cotton", "soft"],
    colors: ["White", "Sky Blue"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-04",
  },
  {
    id: "panjabi-3",
    name: "Embroidered Panjabi",
    slug: "embroidered-panjabi",
    price: 2600,
    originalPrice: 3000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description: "Embroidered panjabi for festive occasions.",
    shortDescription: "Embroidered panjabi",
    rating: 4.8,
    reviewCount: 88,
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    tags: ["embroidered", "festive"],
    colors: ["Cream", "Maroon"],
    sizes: ["L", "XL", "XXL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-07",
  },
  {
    id: "panjabi-4",
    name: "Linen Panjabi",
    slug: "linen-panjabi",
    price: 2700,
    originalPrice: 3200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description: "Linen panjabi for a premium feel.",
    shortDescription: "Linen panjabi",
    rating: 4.6,
    reviewCount: 73,
    inStock: true,
    stockCount: 14,
    isFeatured: true,
    tags: ["linen", "premium"],
    colors: ["Light Blue", "White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Linen",
    createdAt: "2024-02-10",
  },
  {
    id: "panjabi-5",
    name: "Festive Panjabi",
    slug: "festive-panjabi",
    price: 2500,
    originalPrice: 2900,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description: "Festive panjabi with elegant design.",
    shortDescription: "Festive panjabi",
    rating: 4.5,
    reviewCount: 61,
    inStock: true,
    stockCount: 12,
    isFeatured: true,
    tags: ["festive", "elegant"],
    colors: ["White", "Pink"],
    sizes: ["L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-13",
  },
  {
    id: "panjabi-6",
    name: "Premium Black Panjabi",
    slug: "premium-black-panjabi",
    price: 2800,
    originalPrice: 3300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description: "Premium black panjabi for special events.",
    shortDescription: "Premium black panjabi",
    rating: 4.9,
    reviewCount: 49,
    inStock: true,
    stockCount: 10,
    isFeatured: true,
    tags: ["premium", "black"],
    colors: ["Black"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-16",
  },
  {
    id: "panjabi-7",
    name: "Casual Panjabi",
    slug: "casual-panjabi",
    price: 2000,
    originalPrice: 2300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Panjabi",
    categorySlug: "panjabi",
    description: "Casual panjabi for everyday wear.",
    shortDescription: "Casual panjabi",
    rating: 4.3,
    reviewCount: 33,
    inStock: true,
    stockCount: 8,
    isFeatured: true,
    tags: ["casual"],
    colors: ["White", "Blue"],
    sizes: ["S", "M", "L"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-19",
  },

  // --- Polo Shirt ---
  {
    id: "polo-1",
    name: "Premium Polo Shirt",
    slug: "premium-polo-shirt",
    price: 1800,
    originalPrice: 2200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description:
      "Premium quality polo shirt made from breathable cotton blend. Features classic collar design and comfortable fit.",
    shortDescription: "Premium cotton blend polo shirt",
    rating: 4.5,
    reviewCount: 73,
    inStock: true,
    stockCount: 56,
    isFeatured: true,
    isOnSale: true,
    tags: ["polo", "casual", "breathable"],
    colors: ["Navy", "White", "Maroon", "Gray"],
    sizes: ["S", "M", "L", "XL"],
    brand: "DeenCommerce",
    material: "60% Cotton, 40% Polyester",
    createdAt: "2024-01-25",
  },
  {
    id: "polo-2",
    name: "Striped Polo Shirt",
    slug: "striped-polo-shirt",
    price: 1700,
    originalPrice: 2100,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description: "Striped polo shirt for a sporty look.",
    shortDescription: "Striped polo shirt",
    rating: 4.3,
    reviewCount: 52,
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    tags: ["striped", "sporty"],
    colors: ["Blue", "White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-01-28",
  },
  {
    id: "polo-3",
    name: "Casual Polo Shirt",
    slug: "casual-polo-shirt",
    price: 1600,
    originalPrice: 2000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description: "Casual polo shirt for everyday wear.",
    shortDescription: "Casual polo shirt",
    rating: 4.2,
    reviewCount: 38,
    inStock: true,
    stockCount: 35,
    isFeatured: true,
    tags: ["casual"],
    colors: ["Gray", "Black"],
    sizes: ["S", "M", "L"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-01",
  },
  {
    id: "polo-4",
    name: "Classic White Polo",
    slug: "classic-white-polo",
    price: 1750,
    originalPrice: 2100,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description: "Classic white polo shirt for a timeless look.",
    shortDescription: "Classic white polo shirt",
    rating: 4.4,
    reviewCount: 41,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    tags: ["classic", "white"],
    colors: ["White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-04",
  },
  {
    id: "polo-5",
    name: "Navy Blue Polo Shirt",
    slug: "navy-blue-polo-shirt",
    price: 1850,
    originalPrice: 2200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description: "Navy blue polo shirt for a smart casual look.",
    shortDescription: "Navy blue polo shirt",
    rating: 4.6,
    reviewCount: 36,
    inStock: true,
    stockCount: 22,
    isFeatured: true,
    tags: ["navy", "blue"],
    colors: ["Navy"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-07",
  },
  {
    id: "polo-6",
    name: "Maroon Polo Shirt",
    slug: "maroon-polo-shirt",
    price: 1900,
    originalPrice: 2300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description: "Maroon polo shirt for a bold statement.",
    shortDescription: "Maroon polo shirt",
    rating: 4.5,
    reviewCount: 29,
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    isNew: true,
    tags: ["maroon"],
    colors: ["Maroon"],
    sizes: ["L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-10",
  },
  {
    id: "polo-7",
    name: "Sporty Polo Shirt",
    slug: "sporty-polo-shirt",
    price: 1650,
    originalPrice: 2000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Polo Shirt",
    categorySlug: "polo-shirt",
    description: "Sporty polo shirt for active days.",
    shortDescription: "Sporty polo shirt",
    rating: 4.3,
    reviewCount: 21,
    inStock: true,
    stockCount: 12,
    isFeatured: true,
    isNew: true,
    tags: ["sporty"],
    colors: ["Blue", "White"],
    sizes: ["M", "L"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-13",
  },

  // --- T-Shirt ---
  {
    id: "tshirt-1",
    name: "Casual Cotton T-Shirt",
    slug: "casual-cotton-t-shirt",
    price: 1200,
    originalPrice: 1500,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description:
      "Comfortable casual t-shirt made from soft cotton fabric. Perfect for everyday wear with excellent breathability.",
    shortDescription: "Comfortable casual cotton t-shirt",
    rating: 4.4,
    reviewCount: 102,
    inStock: true,
    stockCount: 78,
    isFeatured: true,
    isNew: true,
    tags: ["casual", "comfortable", "cotton"],
    colors: ["Black", "White", "Navy", "Gray", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand: "DeenCommerce",
    material: "100% Cotton",
    createdAt: "2024-02-05",
  },
  {
    id: "tshirt-2",
    name: "Graphic Print T-Shirt",
    slug: "graphic-print-t-shirt",
    price: 1300,
    originalPrice: 1600,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description: "Graphic print t-shirt for a trendy look.",
    shortDescription: "Graphic print t-shirt",
    rating: 4.3,
    reviewCount: 85,
    inStock: true,
    stockCount: 60,
    isFeatured: true,
    tags: ["graphic", "print"],
    colors: ["White", "Black"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-08",
  },
  {
    id: "tshirt-3",
    name: "V-Neck T-Shirt",
    slug: "v-neck-t-shirt",
    price: 1250,
    originalPrice: 1500,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description: "V-neck t-shirt for a stylish appearance.",
    shortDescription: "V-neck t-shirt",
    rating: 4.2,
    reviewCount: 70,
    inStock: true,
    stockCount: 50,
    isFeatured: true,
    tags: ["v-neck", "stylish"],
    colors: ["Navy", "Gray"],
    sizes: ["S", "M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-11",
  },
  {
    id: "tshirt-4",
    name: "Round Neck T-Shirt",
    slug: "round-neck-t-shirt",
    price: 1150,
    originalPrice: 1400,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description: "Round neck t-shirt for classic comfort.",
    shortDescription: "Round neck t-shirt",
    rating: 4.1,
    reviewCount: 62,
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    isNew: true,
    tags: ["round-neck", "classic"],
    colors: ["Black", "White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-14",
  },
  {
    id: "tshirt-5",
    name: "Striped T-Shirt",
    slug: "striped-t-shirt",
    price: 1350,
    originalPrice: 1600,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description: "Striped t-shirt for a modern look.",
    shortDescription: "Striped t-shirt",
    rating: 4.3,
    reviewCount: 55,
    inStock: true,

    stockCount: 35,
    isFeatured: true,
    isNew: true,
    tags: ["striped", "modern"],
    colors: ["Blue", "White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-17",
  },
  {
    id: "tshirt-6",
    name: "Long Sleeve T-Shirt",
    slug: "long-sleeve-t-shirt",
    price: 1450,
    originalPrice: 1700,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description: "Long sleeve t-shirt for cooler days.",
    shortDescription: "Long sleeve t-shirt",
    rating: 4.4,
    reviewCount: 48,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    tags: ["long-sleeve", "cool"],
    colors: ["Gray", "Black"],
    sizes: ["L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-20",
  },
  {
    id: "tshirt-7",
    name: "Basic White T-Shirt",
    slug: "basic-white-t-shirt",
    price: 1100,
    originalPrice: 1300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "T-Shirt",
    categorySlug: "t-shirt",
    description: "Basic white t-shirt for everyday use.",
    shortDescription: "Basic white t-shirt",
    rating: 4.0,
    reviewCount: 33,
    inStock: true,
    stockCount: 20,
    isFeatured: true,
    tags: ["basic", "white"],
    colors: ["White"],
    sizes: ["S", "M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-23",
  },

  // --- Shirt ---
  {
    id: "shirt-1",
    name: "Formal Dress Shirt",
    slug: "formal-dress-shirt",
    price: 2500,
    originalPrice: 3000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description:
      "Professional formal dress shirt with slim fit design. Made from premium cotton blend for office and formal occasions.",
    shortDescription: "Professional slim fit formal shirt",
    rating: 4.7,
    reviewCount: 67,
    inStock: true,
    stockCount: 34,
    isFeatured: true,
    isOnSale: true,
    tags: ["formal", "slim-fit", "professional"],
    colors: ["White", "Light Blue", "Pink"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand: "DeenCommerce",
    material: "70% Cotton, 30% Polyester",
    createdAt: "2024-01-30",
  },
  {
    id: "shirt-2",
    name: "Casual Check Shirt",
    slug: "casual-check-shirt",
    price: 2200,
    originalPrice: 2600,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description: "Casual check shirt for a relaxed look.",
    shortDescription: "Casual check shirt",
    rating: 4.5,
    reviewCount: 54,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    tags: ["casual", "check"],
    colors: ["Blue", "Red"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-02",
  },
  {
    id: "shirt-3",
    name: "Slim Fit White Shirt",
    slug: "slim-fit-white-shirt",
    price: 2400,
    originalPrice: 2800,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description: "Slim fit white shirt for a sharp look.",
    shortDescription: "Slim fit white shirt",
    rating: 4.6,
    reviewCount: 49,
    inStock: true,
    stockCount: 22,
    isFeatured: true,
    tags: ["slim-fit", "white"],
    colors: ["White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-05",
  },
  {
    id: "shirt-4",
    name: "Classic Blue Shirt",
    slug: "classic-blue-shirt",
    price: 2300,
    originalPrice: 2700,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description: "Classic blue shirt for formal and casual wear.",
    shortDescription: "Classic blue shirt",
    rating: 4.4,
    reviewCount: 38,
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    tags: ["classic", "blue"],
    colors: ["Blue"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-08",
  },
  {
    id: "shirt-5",
    name: "Striped Formal Shirt",
    slug: "striped-formal-shirt",
    price: 2600,
    originalPrice: 3100,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description: "Striped formal shirt for a professional look.",
    shortDescription: "Striped formal shirt",
    rating: 4.5,
    reviewCount: 31,
    inStock: true,
    stockCount: 14,
    isFeatured: true,
    tags: ["striped", "formal"],
    colors: ["White", "Blue"],
    sizes: ["L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-11",
  },
  {
    id: "shirt-6",
    name: "Linen Summer Shirt",
    slug: "linen-summer-shirt",
    price: 2700,
    originalPrice: 3200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description: "Linen summer shirt for hot days.",
    shortDescription: "Linen summer shirt",
    rating: 4.3,
    reviewCount: 22,
    inStock: true,
    stockCount: 10,
    isFeatured: true,
    tags: ["linen", "summer"],
    colors: ["White", "Light Blue"],
    sizes: ["M", "L"],
    brand: "DeenCommerce",
    material: "Linen",
    createdAt: "2024-02-14",
  },
  {
    id: "shirt-7",
    name: "Casual Black Shirt",
    slug: "casual-black-shirt",
    price: 2100,
    originalPrice: 2500,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Shirt",
    categorySlug: "shirt",
    description: "Casual black shirt for everyday style.",
    shortDescription: "Casual black shirt",
    rating: 4.2,
    reviewCount: 17,
    inStock: true,
    stockCount: 8,
    isFeatured: true,
    tags: ["casual", "black"],
    colors: ["Black"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-17",
  },

  // --- Accessories ---
  {
    id: "accessories-1",
    name: "Premium Leather Wallet",
    slug: "premium-leather-wallet",
    price: 1500,
    originalPrice: 1800,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description:
      "Handcrafted premium leather wallet with multiple card slots and bill compartments. Elegant design for the modern gentleman.",
    shortDescription: "Handcrafted premium leather wallet",
    rating: 4.8,
    reviewCount: 91,
    inStock: true,
    stockCount: 23,
    isFeatured: true,
    isBestSeller: true,
    isOnSale: true,
    tags: ["leather", "premium", "handcrafted"],
    colors: ["Brown", "Black"],
    brand: "DeenCommerce",
    material: "Genuine Leather",
    createdAt: "2024-01-18",
  },
  {
    id: "accessories-2",
    name: "Classic Sunglasses",
    slug: "classic-sunglasses",
    price: 1200,
    originalPrice: 1500,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description: "Classic sunglasses with UV protection.",
    shortDescription: "Classic sunglasses",
    rating: 4.6,
    reviewCount: 61,
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    tags: ["sunglasses", "classic"],
    colors: ["Black", "Brown"],
    brand: "DeenCommerce",
    material: "Plastic",
    createdAt: "2024-01-21",
  },
  {
    id: "accessories-3",
    name: "Leather Belt",
    slug: "leather-belt",
    price: 1000,
    originalPrice: 1300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description: "Genuine leather belt for formal and casual wear.",
    shortDescription: "Genuine leather belt",
    rating: 4.5,
    reviewCount: 48,
    inStock: true,
    stockCount: 15,
    isFeatured: true,
    tags: ["leather", "belt"],
    colors: ["Black", "Brown"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Leather",
    createdAt: "2024-01-24",
  },
  {
    id: "accessories-4",
    name: "Stylish Cap",
    slug: "stylish-cap",
    price: 800,
    originalPrice: 1000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description: "Stylish cap for sunny days.",
    shortDescription: "Stylish cap",
    rating: 4.4,
    reviewCount: 33,
    inStock: true,
    stockCount: 12,
    isFeatured: true,
    tags: ["cap", "stylish"],
    colors: ["Black", "Blue"],
    sizes: ["Free"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-01-27",
  },
  {
    id: "accessories-5",
    name: "Travel Backpack",
    slug: "travel-backpack",
    price: 2200,
    originalPrice: 2600,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description: "Travel backpack with multiple compartments.",
    shortDescription: "Travel backpack",
    rating: 4.7,
    reviewCount: 29,
    inStock: true,
    stockCount: 10,
    isFeatured: true,
    tags: ["backpack", "travel"],
    colors: ["Black", "Gray"],
    brand: "DeenCommerce",
    material: "Polyester",
    createdAt: "2024-01-30",
  },
  {
    id: "accessories-6",
    name: "Sports Watch",
    slug: "sports-watch",
    price: 3500,
    originalPrice: 4000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description: "Sports watch with water resistance.",
    shortDescription: "Sports watch",
    rating: 4.8,
    reviewCount: 21,
    inStock: true,
    stockCount: 8,
    isFeatured: true,
    tags: ["watch", "sports"],
    colors: ["Black", "Blue"],
    brand: "DeenCommerce",
    material: "Plastic",
    createdAt: "2024-02-02",
  },
  {
    id: "accessories-7",
    name: "Cotton Socks (Pack of 3)",
    slug: "cotton-socks-pack-3",
    price: 600,
    originalPrice: 800,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Accessories",
    categorySlug: "accessories",
    description: "Pack of 3 cotton socks for daily comfort.",
    shortDescription: "Cotton socks pack",
    rating: 4.3,
    reviewCount: 17,
    inStock: true,
    stockCount: 20,
    isFeatured: true,
    tags: ["socks", "cotton"],
    colors: ["Black", "White", "Gray"],
    sizes: ["Free"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-05",
  },

  // --- Boxer ---
  {
    id: "boxer-1",
    name: "Cotton Boxer Shorts",
    slug: "cotton-boxer-shorts",
    price: 800,
    originalPrice: 1000,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description:
      "Comfortable cotton boxer shorts with breathable fabric and elastic waistband. Perfect for everyday comfort and support.",
    shortDescription: "Comfortable cotton boxer shorts",
    rating: 4.3,
    reviewCount: 145,
    inStock: true,
    stockCount: 67,
    isFeatured: true,
    isOnSale: true,
    tags: ["comfortable", "cotton", "breathable"],
    colors: ["Navy", "Black", "Gray", "White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand: "DeenCommerce",
    material: "95% Cotton, 5% Elastane",
    createdAt: "2024-02-03",
  },
  {
    id: "boxer-2",
    name: "Printed Boxer Shorts",
    slug: "printed-boxer-shorts",
    price: 850,
    originalPrice: 1100,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description: "Printed boxer shorts for a fun look.",
    shortDescription: "Printed boxer shorts",
    rating: 4.2,
    reviewCount: 98,
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    tags: ["printed", "fun"],
    colors: ["Blue", "White"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-06",
  },
  {
    id: "boxer-3",
    name: "Classic Black Boxer",
    slug: "classic-black-boxer",
    price: 900,
    originalPrice: 1200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description: "Classic black boxer for everyday use.",
    shortDescription: "Classic black boxer",
    rating: 4.4,
    reviewCount: 77,
    inStock: true,
    stockCount: 35,
    isFeatured: true,
    tags: ["classic", "black"],
    colors: ["Black"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-09",
  },
  {
    id: "boxer-4",
    name: "Breathable Boxer Shorts",
    slug: "breathable-boxer-shorts",
    price: 950,
    originalPrice: 1200,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description: "Breathable boxer shorts for extra comfort.",
    shortDescription: "Breathable boxer shorts",
    rating: 4.5,
    reviewCount: 61,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    tags: ["breathable", "comfort"],
    colors: ["Gray", "White"],
    sizes: ["L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-12",
  },
  {
    id: "boxer-5",
    name: "Colorful Boxer Pack",
    slug: "colorful-boxer-pack",
    price: 1000,
    originalPrice: 1300,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description: "Pack of colorful boxers for variety.",
    shortDescription: "Colorful boxer pack",
    rating: 4.3,
    reviewCount: 44,
    inStock: true,
    stockCount: 20,
    isFeatured: true,
    tags: ["colorful", "pack"],
    colors: ["Red", "Blue", "Green"],
    sizes: ["M", "L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-15",
  },
  {
    id: "boxer-6",
    name: "Premium Boxer Shorts",
    slug: "premium-boxer-shorts",
    price: 1100,
    originalPrice: 1400,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description: "Premium boxer shorts for luxury comfort.",
    shortDescription: "Premium boxer shorts",
    rating: 4.6,
    reviewCount: 29,
    inStock: true,
    stockCount: 15,
    isFeatured: true,
    tags: ["premium", "luxury"],
    colors: ["Black", "Gray"],
    sizes: ["L", "XL"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-18",
  },
  {
    id: "boxer-7",
    name: "Everyday Boxer Shorts",
    slug: "everyday-boxer-shorts",
    price: 850,
    originalPrice: 1100,
    imageUrl: "/images/categories/sample-product.webp",
    images: ["/images/categories/sample-product-2.webp"],
    category: "Boxer",
    categorySlug: "boxer",
    description: "Everyday boxer shorts for daily use.",
    shortDescription: "Everyday boxer shorts",
    rating: 4.1,
    reviewCount: 18,
    inStock: true,
    stockCount: 10,
    isFeatured: true,
    tags: ["everyday"],
    colors: ["Navy", "Black"],
    sizes: ["M", "L"],
    brand: "DeenCommerce",
    material: "Cotton",
    createdAt: "2024-02-21",
  },
];

// Helper functions
export const getProductsByCategory = (categorySlug: string): Product[] => {
  return featuredProducts.filter(
    (product) => product.categorySlug === categorySlug
  );
};

export const getFeaturedProducts = (limit?: number): Product[] => {
  const featured = featuredProducts.filter((product) => product.isFeatured);
  return limit ? featured.slice(0, limit) : featured;
};

export const getBestSellerProducts = (limit?: number): Product[] => {
  const bestSellers = featuredProducts.filter(
    (product) => product.isBestSeller
  );
  return limit ? bestSellers.slice(0, limit) : bestSellers;
};

export const getNewProducts = (limit?: number): Product[] => {
  const newProducts = featuredProducts.filter((product) => product.isNew);
  return limit ? newProducts.slice(0, limit) : newProducts;
};

export const getSaleProducts = (limit?: number): Product[] => {
  const saleProducts = featuredProducts.filter((product) => product.isOnSale);
  return limit ? saleProducts.slice(0, limit) : saleProducts;
};

export const getProductById = (id: string): Product | undefined => {
  return featuredProducts.find((product) => product.id === id);
};

export const getProductBySlug = (slug: string): Product | undefined => {
  return featuredProducts.find((product) => product.slug === slug);
};

// Calculate discount percentage
export const getDiscountPercentage = (
  originalPrice: number,
  currentPrice: number
): number => {
  return Math.round(((originalPrice - currentPrice) / originalPrice) * 100);
};

// Format price for display
export const formatPrice = (price: number): string => {
  return `৳${price.toLocaleString()}`;
};
